version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: local
        ports:
            - "9009:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APACHE_DOCUMENT_ROOT: /var/www/html/public
        depends_on:
            - db
        container_name: my_app_container

    db:
        image: mysql:5.7
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        container_name: my_db_container

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "9002:80"
        environment:
            - PMA_ARBITRARY=1
        container_name: my_phpmyadmin_container

volumes:
    db_data:
