version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: local
        ports:
            - "9009:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APACHE_DOCUMENT_ROOT: /var/www/html/public
            TZ: "America/Argentina/Buenos_Aires"
        depends_on:
            - db
            - redis  # Añadido aquí para asegurar que Redis esté disponible
        container_name: my_app_container
        deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: '3g'

    db:
        image: mysql:5.7
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            TZ: "America/Argentina/Buenos_Aires"
        volumes:
            - db_data:/var/lib/mysql
        container_name: my_db_container
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: '2g'

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "9002:80"
        environment:
            - PMA_ARBITRARY=1
        container_name: my_phpmyadmin_container

    redis:  # Servicio de Redis agregado
        image: redis:latest
        ports:
            - "6379:6379"  # Puertos de Redis
        container_name: my_redis_container
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: '2g'

volumes:
    db_data:
