version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/html
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public
        depends_on:
            - db

    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
